# Dataset generation config.

mode = "normal"
output_dir = "../data/datasets/lv6-18"
phases = "20..60"
samples_per_phase = 100000

[split]
train = 0.98
valid = 0.01
test = 0.01

[playout]
ai_probability = 0.33
dedupe = "canonical_board"
max_attempts_multiplier = 100

[playout.ai]
# name = "edax"
name = "edax"
level = 6
threads = 1
timeout = "10s"

[self_play]
workers = 19
retries = 3

[self_play.ai]
name = "edax"
level = 12
threads = 1
timeout = "300s"

[window]
enabled = true
size = 10
